### ISSUE TITLE
Chat message time label alignment

### ISSUE THREAD

**Issue by jessedvrs** [part-up/app#42]
The time label isn't aligned to the right when the text takes more than one line. Probably easy to fix using `float: right;`

![img_1626](https://cloud.githubusercontent.com/assets/5961598/15603240/e32791ea-23f9-11e6-807d-9fad83949bdd.PNG)

**Comment by jessedvrs** [comment]
Fixed with #77

**Comment by ralphboeije** [comment]
@jessedvrs I still see this in the latest version of the app so I don't think it is fixed?

**Comment by jessedvrs** [comment]
In issue #77 you can see it's fixed in 10a3fd89c8ff2f164c3c722942d857d8ea395507 which is a commit made after the release of 1.2.3. So in 1.2.4 it will be fixed!

![screen shot 2016-06-15 at 17 46 57](https://cloud.githubusercontent.com/assets/5961598/16111765/532a7394-33b4-11e6-9511-8473b08dd45b.png)

**Comment by ralphboeije** [comment]
Great @jessedvrs thought it was fixed in 1.2.3 so that's where the confusing came from. Does this also include a fix for the multiline timestamp alignment (right and inline) as designed: https://redpen.io/am452b9898b111a148?

**Comment by jessedvrs** [comment]
From 1.2.4 on, times won't be rendered inside messages anymore. Only below a group of messages in a timeframe of 3 minutes. So multiline messages won't affect time label alignment anymore.

**Comment by ralphboeije** [comment]
cool
